# -*- coding: utf-8 -*-
"""pages_development.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z20pqwhwdVa4qSM0hIsAPwljavCWgt6_
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import joblib

import os

print(os.listdir("/content"))

resume_df = pd.read_csv("/content/resume_data.csv")
salary_df = pd.read_csv("ds_salaries.csv")
jobs_df = pd.read_csv("DataAnalyst.csv.zip", compression="zip")
people_df = pd.read_csv("01_people.csv")

# ==========================
# HOME PAGE
# ==========================

st.title("🤖 AI Resume & Job Market Analytics")

st.markdown("""
Welcome to the project.

### Features
- 📊 EDA
- 📄 ATS Score
- 🧠 Skill Gap
- 💼 Job Recommendation
- 💰 Salary Prediction
- 📈 Salary Analytics
- 🏆 Resume Ranking
""")

# ==========================
# EDA PAGE
# ==========================

st.header("📊 Exploratory Data Analysis")

st.write("Resume Dataset")
st.dataframe(resume_df.head())

st.write("Salary Dataset")
st.dataframe(salary_df.head())

st.write("Jobs Dataset")
st.dataframe(jobs_df.head())

# ==========================
# ATS PAGE
# ==========================

st.header("📄 ATS Resume Score")

ats_score = 40

st.metric("ATS Score", f"{ats_score}%")

# ==========================
# AI Job Recommendation
# ==========================

print("AI Job Recommendation")

# Sample candidate skills
candidate_skills = [
    "python",
    "machine learning",
    "sql",
    "data science",
    "statistics"
]

# Check if DataAnalyst.csv has a Job Description column
if "Job Description" in jobs_df.columns:
    recommendations = []

    for _, row in jobs_df.iterrows():
        description = str(row["Job Description"]).lower()

        score = sum(skill in description for skill in candidate_skills)

        recommendations.append(score)

    jobs_df["Match Score"] = recommendations

    top_jobs = jobs_df.sort_values("Match Score", ascending=False).head(5)

    print(top_jobs[["Job Title", "Company Name", "Location", "Match Score"]])

else:
    print("Job Description column not found!")
    print("Available columns:")
    print(jobs_df.columns)

print(jobs_df.columns.tolist())

import matplotlib.pyplot as plt
import seaborn as sns

# Remove unwanted column if it exists
salary_df = salary_df.drop(columns=["Unnamed: 0"], errors="ignore")

# Display first few rows
print(salary_df.head())

# Basic information
print(salary_df.info())

# Average Salary by Experience Level
avg_salary = salary_df.groupby("experience_level")["salary_in_usd"].mean().sort_values()

plt.figure(figsize=(8,5))
avg_salary.plot(kind="bar", color="skyblue")
plt.title("Average Salary by Experience Level")
plt.xlabel("Experience Level")
plt.ylabel("Average Salary (USD)")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(7,5))

salary_df["company_size"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.title("Company Size Distribution")
plt.ylabel("")
plt.show()

plt.figure(figsize=(10,5))

salary_df["company_location"].value_counts().head(10).plot(
    kind="bar",
    color="green"
)

plt.title("Top 10 Hiring Countries")
plt.xlabel("Country")
plt.ylabel("Number of Jobs")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(6,4))

sns.countplot(
    data=salary_df,
    x="remote_ratio"
)

plt.title("Remote Work Distribution")
plt.xlabel("Remote Ratio")
plt.ylabel("Count")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Copy dataset
salary_ml = salary_df.copy()

# Remove unnecessary column if present
salary_ml = salary_ml.drop(columns=["Unnamed: 0"], errors="ignore")

# Encode categorical columns
encoder = LabelEncoder()

categorical_cols = [
    "experience_level",
    "employment_type",
    "job_title",
    "salary_currency",
    "employee_residence",
    "company_location",
    "company_size"
]

for col in categorical_cols:
    salary_ml[col] = encoder.fit_transform(salary_ml[col].astype(str))

# Features and Target
X = salary_ml.drop(["salary", "salary_in_usd"], axis=1)
y = salary_ml["salary_in_usd"]

print(X.head())

from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Trained Successfully!")

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

pred = model.predict(X_test)

print("MAE :", mean_absolute_error(y_test, pred))
print("RMSE:", mean_squared_error(y_test, pred) ** 0.5)
print("R² Score:", r2_score(y_test, pred))

import joblib

joblib.dump(model, "salary_prediction_model.pkl")

print("Model Saved Successfully!")

sample = X.iloc[[0]]

prediction = model.predict(sample)

print("Predicted Salary (USD):", round(prediction[0], 2))
print("Actual Salary (USD):", y.iloc[0])

from google.colab import files

uploaded = files.upload()

print("="*60)
print("🤖 AI Resume & Job Market Analytics")
print("="*60)

print("✅ Resume Parsing Completed")
print("✅ ATS Score Calculation Completed")
print("✅ Skill Gap Analysis Completed")
print("✅ AI Job Recommendation Completed")
print("✅ Salary Analytics Completed")
print("✅ Salary Prediction Completed")

print("\n🎉 Project Successfully Completed!")

import joblib

joblib.dump(model, "salary_prediction_model.pkl")

resume_df.to_csv("clean_resume.csv", index=False)
salary_df.to_csv("clean_salary.csv", index=False)
jobs_df.to_csv("clean_jobs.csv", index=False)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# 
# st.set_page_config(
#     page_title="AI Resume & Job Market Analytics",
#     page_icon="🤖",
#     layout="wide"
# )
# 
# st.title("🤖 AI Resume & Job Market Analytics")
# 
# st.write("Welcome to my Final Year Data Analytics Project!")
# 
# st.markdown("""
# ### Features
# - 📊 EDA
# - 📄 ATS Score
# - 🧠 Skill Gap Analysis
# - 💼 Job Recommendation
# - 💰 Salary Prediction
# - 📈 Salary Analytics
# 
# 👈 Choose a page from the sidebar.
# """)

!streamlit run app.py

